command_index: https://drdeee.github.io/matrix-help-index/commands.json
category_index: https://drdeee.github.io/matrix-help-index/categories.json
standard_category: Weiteres
devs:
  - "@deee:fff.chat"
  - "@asklios:fff.chat"